# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'raedict'
primary_region = 'gru'

[build]
  dockerfile = "Dockerfile"
  # Build locally instead of using remote builders
  local_only = true

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "2628"

[[services]]
  internal_port = 2628
  protocol = "tcp"

  [[services.ports]]
    port = 2628

# optional but recommended if using long-lived connections
# [services.tcp_checks]
#   interval = "15s"
#   timeout  = "2s"